version: "3.8"
services:
    caddy:
        restart: unless-stopped
        image: caddy:latest
        container_name: server-caddy
        ports:
            - "443:443"
        volumes:
            - "./data/typecho:/www/wwwroot/typecho"
            - "./config:/etc/caddy"
            - "./logs:/www/wwwlogs"
        networks:
            - typecho-network
    php:
        restart: unless-stopped
        container_name: server-php
        image: johnsonran/server-php:latest
        volumes:
            - "./data:/www/wwwroot"
        networks:
            - typecho-network
    mysql:
        restart: unless-stopped
        image: mysql:latest
        container_name: server-mysql
        ports:
            - "127.0.0.1:3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=PMA_PASSWD
        networks:
            - typecho-network
    pma:
        restart: unless-stopped
        image: phpmyadmin:latest
        container_name: server-pma
        ports:
            - "8283:80"
        environment:
            - PMA_HOST=server-mysql
            - PMA_PORT=3306
        networks:
            - typecho-network
networks:
    typecho-network:
        driver: bridge
