name: Build and Push the Docker image
on: 
  push:
    branches:
    - main
    paths:
    - 'app/php/Dockerfile'
jobs:
  Build:
    runs-on: 
    - ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
          cd app/php
          docker build . --file Dockerfile --tag johnsonran/server-php:latest

    - name: Login DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.HUB_USR }}
          password: ${{ secrets.HUB_TKN }}

    - name: Push to DockerHub
      run: |
          docker push johnsonran/server-php:latest